// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.2
// source: administrator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsageScratch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int64  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Date   string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *UsageScratch) Reset() {
	*x = UsageScratch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsageScratch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageScratch) ProtoMessage() {}

func (x *UsageScratch) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageScratch.ProtoReflect.Descriptor instead.
func (*UsageScratch) Descriptor() ([]byte, []int) {
	return file_administrator_proto_rawDescGZIP(), []int{0}
}

func (x *UsageScratch) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UsageScratch) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type UsageComposition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int64  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Date   string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *UsageComposition) Reset() {
	*x = UsageComposition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsageComposition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageComposition) ProtoMessage() {}

func (x *UsageComposition) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageComposition.ProtoReflect.Descriptor instead.
func (*UsageComposition) Descriptor() ([]byte, []int) {
	return file_administrator_proto_rawDescGZIP(), []int{1}
}

func (x *UsageComposition) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UsageComposition) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ForWhat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int64  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ForWhat) Reset() {
	*x = ForWhat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForWhat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForWhat) ProtoMessage() {}

func (x *ForWhat) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForWhat.ProtoReflect.Descriptor instead.
func (*ForWhat) Descriptor() ([]byte, []int) {
	return file_administrator_proto_rawDescGZIP(), []int{2}
}

func (x *ForWhat) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ForWhat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Usage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scratch     []*UsageScratch     `protobuf:"bytes,1,rep,name=scratch,proto3" json:"scratch,omitempty"`
	Composition []*UsageComposition `protobuf:"bytes,2,rep,name=composition,proto3" json:"composition,omitempty"`
	ForWhat     []*ForWhat          `protobuf:"bytes,3,rep,name=forWhat,proto3" json:"forWhat,omitempty"`
}

func (x *Usage) Reset() {
	*x = Usage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_administrator_proto_rawDescGZIP(), []int{3}
}

func (x *Usage) GetScratch() []*UsageScratch {
	if x != nil {
		return x.Scratch
	}
	return nil
}

func (x *Usage) GetComposition() []*UsageComposition {
	if x != nil {
		return x.Composition
	}
	return nil
}

func (x *Usage) GetForWhat() []*ForWhat {
	if x != nil {
		return x.ForWhat
	}
	return nil
}

type ExecutionUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Opt    int32  `protobuf:"varint,2,opt,name=opt,proto3" json:"opt,omitempty"`
}

func (x *ExecutionUserRequest) Reset() {
	*x = ExecutionUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutionUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionUserRequest) ProtoMessage() {}

func (x *ExecutionUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionUserRequest.ProtoReflect.Descriptor instead.
func (*ExecutionUserRequest) Descriptor() ([]byte, []int) {
	return file_administrator_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutionUserRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ExecutionUserRequest) GetOpt() int32 {
	if x != nil {
		return x.Opt
	}
	return 0
}

type ExecutionCreationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Opt int32 `protobuf:"varint,2,opt,name=opt,proto3" json:"opt,omitempty"`
}

func (x *ExecutionCreationRequest) Reset() {
	*x = ExecutionCreationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutionCreationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionCreationRequest) ProtoMessage() {}

func (x *ExecutionCreationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionCreationRequest.ProtoReflect.Descriptor instead.
func (*ExecutionCreationRequest) Descriptor() ([]byte, []int) {
	return file_administrator_proto_rawDescGZIP(), []int{5}
}

func (x *ExecutionCreationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExecutionCreationRequest) GetOpt() int32 {
	if x != nil {
		return x.Opt
	}
	return 0
}

type ExecutionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ExecutionResponse) Reset() {
	*x = ExecutionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResponse) ProtoMessage() {}

func (x *ExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResponse.ProtoReflect.Descriptor instead.
func (*ExecutionResponse) Descriptor() ([]byte, []int) {
	return file_administrator_proto_rawDescGZIP(), []int{6}
}

func (x *ExecutionResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type EditBulletinMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *EditBulletinMsg) Reset() {
	*x = EditBulletinMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditBulletinMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditBulletinMsg) ProtoMessage() {}

func (x *EditBulletinMsg) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditBulletinMsg.ProtoReflect.Descriptor instead.
func (*EditBulletinMsg) Descriptor() ([]byte, []int) {
	return file_administrator_proto_rawDescGZIP(), []int{7}
}

func (x *EditBulletinMsg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TopLikesUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile   string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Likes    int64  `protobuf:"varint,3,opt,name=likes,proto3" json:"likes,omitempty"`
	Motto    string `protobuf:"bytes,4,opt,name=motto,proto3" json:"motto,omitempty"`
	Avatar   string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (x *TopLikesUser) Reset() {
	*x = TopLikesUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopLikesUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopLikesUser) ProtoMessage() {}

func (x *TopLikesUser) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopLikesUser.ProtoReflect.Descriptor instead.
func (*TopLikesUser) Descriptor() ([]byte, []int) {
	return file_administrator_proto_rawDescGZIP(), []int{8}
}

func (x *TopLikesUser) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *TopLikesUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *TopLikesUser) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *TopLikesUser) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

func (x *TopLikesUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type TopReportUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile   string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Report   int64  `protobuf:"varint,3,opt,name=report,proto3" json:"report,omitempty"`
	Motto    string `protobuf:"bytes,4,opt,name=motto,proto3" json:"motto,omitempty"`
	Avatar   string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (x *TopReportUser) Reset() {
	*x = TopReportUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopReportUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopReportUser) ProtoMessage() {}

func (x *TopReportUser) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopReportUser.ProtoReflect.Descriptor instead.
func (*TopReportUser) Descriptor() ([]byte, []int) {
	return file_administrator_proto_rawDescGZIP(), []int{9}
}

func (x *TopReportUser) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *TopReportUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *TopReportUser) GetReport() int64 {
	if x != nil {
		return x.Report
	}
	return 0
}

func (x *TopReportUser) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

func (x *TopReportUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type TopLikesCreation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Likes          int64  `protobuf:"varint,3,opt,name=likes,proto3" json:"likes,omitempty"`
	Mp3            string `protobuf:"bytes,4,opt,name=mp3,proto3" json:"mp3,omitempty"`
	Detail         string `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	Nick           string `protobuf:"bytes,6,opt,name=nick,proto3" json:"nick,omitempty"`
	Avatar         string `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	ChineseNote    string `protobuf:"bytes,8,opt,name=chineseNote,proto3" json:"chineseNote,omitempty"`
	ChineseEmotion string `protobuf:"bytes,9,opt,name=chineseEmotion,proto3" json:"chineseEmotion,omitempty"`
}

func (x *TopLikesCreation) Reset() {
	*x = TopLikesCreation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopLikesCreation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopLikesCreation) ProtoMessage() {}

func (x *TopLikesCreation) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopLikesCreation.ProtoReflect.Descriptor instead.
func (*TopLikesCreation) Descriptor() ([]byte, []int) {
	return file_administrator_proto_rawDescGZIP(), []int{10}
}

func (x *TopLikesCreation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TopLikesCreation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopLikesCreation) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *TopLikesCreation) GetMp3() string {
	if x != nil {
		return x.Mp3
	}
	return ""
}

func (x *TopLikesCreation) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *TopLikesCreation) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *TopLikesCreation) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *TopLikesCreation) GetChineseNote() string {
	if x != nil {
		return x.ChineseNote
	}
	return ""
}

func (x *TopLikesCreation) GetChineseEmotion() string {
	if x != nil {
		return x.ChineseEmotion
	}
	return ""
}

type TopReportCreation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Report         int64  `protobuf:"varint,3,opt,name=report,proto3" json:"report,omitempty"`
	Mp3            string `protobuf:"bytes,4,opt,name=mp3,proto3" json:"mp3,omitempty"`
	Detail         string `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	Nick           string `protobuf:"bytes,6,opt,name=nick,proto3" json:"nick,omitempty"`
	Avatar         string `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	ChineseNote    string `protobuf:"bytes,8,opt,name=chineseNote,proto3" json:"chineseNote,omitempty"`
	ChineseEmotion string `protobuf:"bytes,9,opt,name=chineseEmotion,proto3" json:"chineseEmotion,omitempty"`
}

func (x *TopReportCreation) Reset() {
	*x = TopReportCreation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopReportCreation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopReportCreation) ProtoMessage() {}

func (x *TopReportCreation) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopReportCreation.ProtoReflect.Descriptor instead.
func (*TopReportCreation) Descriptor() ([]byte, []int) {
	return file_administrator_proto_rawDescGZIP(), []int{11}
}

func (x *TopReportCreation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TopReportCreation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopReportCreation) GetReport() int64 {
	if x != nil {
		return x.Report
	}
	return 0
}

func (x *TopReportCreation) GetMp3() string {
	if x != nil {
		return x.Mp3
	}
	return ""
}

func (x *TopReportCreation) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *TopReportCreation) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *TopReportCreation) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *TopReportCreation) GetChineseNote() string {
	if x != nil {
		return x.ChineseNote
	}
	return ""
}

func (x *TopReportCreation) GetChineseEmotion() string {
	if x != nil {
		return x.ChineseEmotion
	}
	return ""
}

type UserAuditResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserLikes  []*TopLikesUser  `protobuf:"bytes,1,rep,name=userLikes,proto3" json:"userLikes,omitempty"`
	UserReport []*TopReportUser `protobuf:"bytes,2,rep,name=userReport,proto3" json:"userReport,omitempty"`
}

func (x *UserAuditResponse) Reset() {
	*x = UserAuditResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuditResponse) ProtoMessage() {}

func (x *UserAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuditResponse.ProtoReflect.Descriptor instead.
func (*UserAuditResponse) Descriptor() ([]byte, []int) {
	return file_administrator_proto_rawDescGZIP(), []int{12}
}

func (x *UserAuditResponse) GetUserLikes() []*TopLikesUser {
	if x != nil {
		return x.UserLikes
	}
	return nil
}

func (x *UserAuditResponse) GetUserReport() []*TopReportUser {
	if x != nil {
		return x.UserReport
	}
	return nil
}

type CreationAuditResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreationLikes  []*TopLikesCreation  `protobuf:"bytes,1,rep,name=creationLikes,proto3" json:"creationLikes,omitempty"`
	CreationReport []*TopReportCreation `protobuf:"bytes,2,rep,name=creationReport,proto3" json:"creationReport,omitempty"`
}

func (x *CreationAuditResponse) Reset() {
	*x = CreationAuditResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreationAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreationAuditResponse) ProtoMessage() {}

func (x *CreationAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreationAuditResponse.ProtoReflect.Descriptor instead.
func (*CreationAuditResponse) Descriptor() ([]byte, []int) {
	return file_administrator_proto_rawDescGZIP(), []int{13}
}

func (x *CreationAuditResponse) GetCreationLikes() []*TopLikesCreation {
	if x != nil {
		return x.CreationLikes
	}
	return nil
}

func (x *CreationAuditResponse) GetCreationReport() []*TopReportCreation {
	if x != nil {
		return x.CreationReport
	}
	return nil
}

type UserFeedback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nickname string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Mobile   string `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Avatar   string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Suspect  string `protobuf:"bytes,4,opt,name=suspect,proto3" json:"suspect,omitempty"`
	Evidence string `protobuf:"bytes,5,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Advice   string `protobuf:"bytes,6,opt,name=advice,proto3" json:"advice,omitempty"`
	Time     int64  `protobuf:"varint,7,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *UserFeedback) Reset() {
	*x = UserFeedback{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFeedback) ProtoMessage() {}

func (x *UserFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFeedback.ProtoReflect.Descriptor instead.
func (*UserFeedback) Descriptor() ([]byte, []int) {
	return file_administrator_proto_rawDescGZIP(), []int{14}
}

func (x *UserFeedback) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserFeedback) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserFeedback) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserFeedback) GetSuspect() string {
	if x != nil {
		return x.Suspect
	}
	return ""
}

func (x *UserFeedback) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *UserFeedback) GetAdvice() string {
	if x != nil {
		return x.Advice
	}
	return ""
}

func (x *UserFeedback) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type UserFeedbackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserFeedback []*UserFeedback `protobuf:"bytes,1,rep,name=userFeedback,proto3" json:"userFeedback,omitempty"`
}

func (x *UserFeedbackResponse) Reset() {
	*x = UserFeedbackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFeedbackResponse) ProtoMessage() {}

func (x *UserFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFeedbackResponse.ProtoReflect.Descriptor instead.
func (*UserFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_administrator_proto_rawDescGZIP(), []int{15}
}

func (x *UserFeedbackResponse) GetUserFeedback() []*UserFeedback {
	if x != nil {
		return x.UserFeedback
	}
	return nil
}

var File_administrator_proto protoreflect.FileDescriptor

var file_administrator_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x0c, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63, 0x72, 0x61, 0x74,
	0x63, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x3e,
	0x0a, 0x10, 0x55, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x35,
	0x0a, 0x07, 0x46, 0x6f, 0x72, 0x57, 0x68, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x89, 0x01, 0x0a, 0x05, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x27, 0x0a, 0x07, 0x73, 0x63, 0x72, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63, 0x72, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x07, 0x73, 0x63, 0x72, 0x61, 0x74, 0x63, 0x68, 0x12, 0x33, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x55, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a,
	0x07, 0x66, 0x6f, 0x72, 0x57, 0x68, 0x61, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x46, 0x6f, 0x72, 0x57, 0x68, 0x61, 0x74, 0x52, 0x07, 0x66, 0x6f, 0x72, 0x57, 0x68, 0x61,
	0x74, 0x22, 0x40, 0x0a, 0x14, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62,
	0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6f, 0x70, 0x74, 0x22, 0x3c, 0x0a, 0x18, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x6f, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6f, 0x70,
	0x74, 0x22, 0x25, 0x0a, 0x11, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x23, 0x0a, 0x0f, 0x45, 0x64, 0x69, 0x74,
	0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x86, 0x01,
	0x0a, 0x0c, 0x54, 0x6f, 0x70, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x74, 0x74,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x74, 0x74, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x89, 0x01, 0x0a, 0x0d, 0x54, 0x6f, 0x70, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x74, 0x74, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x74, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x22, 0xec, 0x01, 0x0a, 0x10, 0x54, 0x6f, 0x70, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6b, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x70, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x70, 0x33, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x69, 0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x73, 0x65, 0x45, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x65, 0x45, 0x6d, 0x6f, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0xef, 0x01, 0x0a, 0x11, 0x54, 0x6f, 0x70, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x70, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x70, 0x33, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x69, 0x63,
	0x6b, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x73, 0x65, 0x45, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x65, 0x45, 0x6d, 0x6f, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x70, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x64, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x4c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x54, 0x6f,
	0x70, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x55, 0x73, 0x65, 0x72, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x4c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x54, 0x6f, 0x70, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x8c, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x75, 0x64, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x37, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6b, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x54, 0x6f, 0x70, 0x4c, 0x69, 0x6b, 0x65,
	0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x0e, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x54, 0x6f, 0x70, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x22, 0xbc, 0x01, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x46, 0x65, 0x65,
	0x64, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65,
	0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65,
	0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x64, 0x76, 0x69, 0x63,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x64, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x22, 0x49, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x46, 0x65, 0x65, 0x64, 0x62,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x75,
	0x73, 0x65, 0x72, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b,
	0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x32, 0xa7,
	0x03, 0x0a, 0x0d, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x2a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x06, 0x2e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x0b,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x0c, 0x45, 0x64, 0x69, 0x74,
	0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x69, 0x6e, 0x12, 0x10, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x42,
	0x75, 0x6c, 0x6c, 0x65, 0x74, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x1a, 0x10, 0x2e, 0x45, 0x64, 0x69,
	0x74, 0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x37, 0x0a, 0x09,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x64, 0x69, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x12, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x64, 0x69, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x41, 0x75, 0x64, 0x69, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x75, 0x64, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x15, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_administrator_proto_rawDescOnce sync.Once
	file_administrator_proto_rawDescData = file_administrator_proto_rawDesc
)

func file_administrator_proto_rawDescGZIP() []byte {
	file_administrator_proto_rawDescOnce.Do(func() {
		file_administrator_proto_rawDescData = protoimpl.X.CompressGZIP(file_administrator_proto_rawDescData)
	})
	return file_administrator_proto_rawDescData
}

var file_administrator_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_administrator_proto_goTypes = []interface{}{
	(*UsageScratch)(nil),             // 0: UsageScratch
	(*UsageComposition)(nil),         // 1: UsageComposition
	(*ForWhat)(nil),                  // 2: ForWhat
	(*Usage)(nil),                    // 3: Usage
	(*ExecutionUserRequest)(nil),     // 4: ExecutionUserRequest
	(*ExecutionCreationRequest)(nil), // 5: ExecutionCreationRequest
	(*ExecutionResponse)(nil),        // 6: ExecutionResponse
	(*EditBulletinMsg)(nil),          // 7: EditBulletinMsg
	(*TopLikesUser)(nil),             // 8: TopLikesUser
	(*TopReportUser)(nil),            // 9: TopReportUser
	(*TopLikesCreation)(nil),         // 10: TopLikesCreation
	(*TopReportCreation)(nil),        // 11: TopReportCreation
	(*UserAuditResponse)(nil),        // 12: UserAuditResponse
	(*CreationAuditResponse)(nil),    // 13: CreationAuditResponse
	(*UserFeedback)(nil),             // 14: UserFeedback
	(*UserFeedbackResponse)(nil),     // 15: UserFeedbackResponse
	(*emptypb.Empty)(nil),            // 16: google.protobuf.Empty
}
var file_administrator_proto_depIdxs = []int32{
	0,  // 0: Usage.scratch:type_name -> UsageScratch
	1,  // 1: Usage.composition:type_name -> UsageComposition
	2,  // 2: Usage.forWhat:type_name -> ForWhat
	8,  // 3: UserAuditResponse.userLikes:type_name -> TopLikesUser
	9,  // 4: UserAuditResponse.userReport:type_name -> TopReportUser
	10, // 5: CreationAuditResponse.creationLikes:type_name -> TopLikesCreation
	11, // 6: CreationAuditResponse.creationReport:type_name -> TopReportCreation
	14, // 7: UserFeedbackResponse.userFeedback:type_name -> UserFeedback
	16, // 8: Administrator.GetUsage:input_type -> google.protobuf.Empty
	4,  // 9: Administrator.ExecuteUser:input_type -> ExecutionUserRequest
	5,  // 10: Administrator.ExecuteCreation:input_type -> ExecutionCreationRequest
	7,  // 11: Administrator.EditBulletin:input_type -> EditBulletinMsg
	16, // 12: Administrator.UserAudit:input_type -> google.protobuf.Empty
	16, // 13: Administrator.CreationAudit:input_type -> google.protobuf.Empty
	16, // 14: Administrator.GetUserFeedback:input_type -> google.protobuf.Empty
	3,  // 15: Administrator.GetUsage:output_type -> Usage
	6,  // 16: Administrator.ExecuteUser:output_type -> ExecutionResponse
	6,  // 17: Administrator.ExecuteCreation:output_type -> ExecutionResponse
	7,  // 18: Administrator.EditBulletin:output_type -> EditBulletinMsg
	12, // 19: Administrator.UserAudit:output_type -> UserAuditResponse
	13, // 20: Administrator.CreationAudit:output_type -> CreationAuditResponse
	15, // 21: Administrator.GetUserFeedback:output_type -> UserFeedbackResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_administrator_proto_init() }
func file_administrator_proto_init() {
	if File_administrator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_administrator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsageScratch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_administrator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsageComposition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_administrator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForWhat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_administrator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Usage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_administrator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutionUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_administrator_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutionCreationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_administrator_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_administrator_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditBulletinMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_administrator_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopLikesUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_administrator_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopReportUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_administrator_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopLikesCreation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_administrator_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopReportCreation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_administrator_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAuditResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_administrator_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreationAuditResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_administrator_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserFeedback); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_administrator_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserFeedbackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_administrator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_administrator_proto_goTypes,
		DependencyIndexes: file_administrator_proto_depIdxs,
		MessageInfos:      file_administrator_proto_msgTypes,
	}.Build()
	File_administrator_proto = out.File
	file_administrator_proto_rawDesc = nil
	file_administrator_proto_goTypes = nil
	file_administrator_proto_depIdxs = nil
}
